title: "SPEARFISH Report"
subtitle: "For de novo transcriptome assembly"
intro_text: "The following report will cover the most important results revealed from analysis."
custom_logo: "./spearfishlogo.png"
custom_logo_width: 200

module_order:
  - fastqc:
      name: "Falco"
  - fastp
  - sortmerna
  - busco

sp:
  fastqc/data:
    fn: "*_data.txt"
    path: "*/falco/*"
  sortmerna:
    fn: "*_sortmerna.log"
  custom_content:
    - fn: "*_ExNX_mqc.yaml"
    - fn: "*_mqc.tsv"

fn_clean_exts:
  - type: regex
    pattern: "short_summary\\..*_odb10\\."
  - ".fq"
  - ".fastq"
  - ".txt"

fn_ignore_files:
  - "short_summary*.json"

report_section_order:
  fastqc_status_checks:
    order: -1000
  exnx:
    order: -1100
  cats_rf_assembly_score:
    order: -1200
  transcript_score_distributions:
    order: -1300
  cats_rf_general_stats:
    order: -1400
  bandage:
    order: -1500
  multiqc_software_versions:
    order: -1600

custom_plot_config:
  fastqc_sequence_counts_plot:
    title: "Falco: Sequence Counts"
  fastqc_per_sequence_quality_scores_plot:
    title: "Falco: Per Sequence GC Content"
  fastqc_per_base_sequence_quality_plot:
    title: "Falco: Mean Quality Scores"
  fastqc_per_sequence_gc_content_plot:
    title: "Falco: Per Sequence GC Content"
  fastqc_per_base_n_content_plot:
    title: "Falco: Per Base N Content"
  fastqc_sequence_length_distribution_plot:
    title: "Falco: Sequence Length Distribution"
  fastqc_sequence_duplication_levels_plot:
    title: "Falco: Sequence Duplication Levels"
  fastqc_overrepresented_sequences_plot:
    title: "Falco: Overrepresented sequences sample summary"
  fastqc_adapter_content_plot:
    title: "Falco: Adapter Content"
  fastqc_status_check_heatmap:
    title: "Falco: Status Checks"